### PR TITLE
fix(dayjs): fix relative time not follow language change

### LINKED ISSUE #3839: After the language switch, the data rendered by dayjs is not updated accordingly
### Platform

Desktop - macOS, Desktop - Web

### Describe the bug

当我们进入页面，默认会显示 `an hour ago`。这样是正常的，当我们切换到中文，会显示 `an hour 前`，这就不对了。看了下代码，前面没有更新的这一部分是 `formatTime` 这个方法生成的，再一看就是 `updateRelativeTime`  的 effect 里没有语言切换的依赖，导致没有更新。

https://github.com/RSSNext/Follow/blob/e656cfd3a2d99079d53876721516d39e273ce05f/packages/internal/components/src/ui/datetime/index.tsx#L12

https://github.com/user-attachments/assets/eda7a4f1-065c-4f57-90f5-a2238bce3ebf

### Relevant Information

_No response_

### Reproduction Video

_No response_

### Environment

_No response_

### Validations

- [x] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [x] This issue is valid

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

### PR DESCRIPTION
**Pull request by cscnk52**
### PR Type

- [ ] Feature
- [x] Bugfix
- [ ] Hotfix
- [ ] Other (please describe):

### Demo Video (if new feature)

https://github.com/user-attachments/assets/72a3f225-c6c7-464a-bf31-bf13b91db179

### Linked Issues

closes #3839 

### Additional context

fix relative time not follow language change

In Chinese and Japanese language, don't use space to separate word, so change space to empty.

also fix an eslint problem. 

### Changelog

- [ ] I have updated the changelog/next.md with my changes.

### CODE REVIEW

File: packages/internal/components/src/ui/datetime/index.tsx [hunk 1]
```diff
@@ -34,6 +34,9 @@ export const RelativeTime: FC<{
 
   const timerRef = useRef<any>(null)
 
+  const { i18n } = useTranslation("common")
+  dayjs.locale(i18n.language)
```
Comment (hyoban) [inline packages/internal/components/src/ui/datetime/index.tsx]: Why do we need to	run it here? Can't we just run it where we switch the language?

Comment (cscnk52) [reply packages/internal/components/src/ui/datetime/index.tsx]: Yes, i will fix it.

File: apps/desktop/layer/renderer/src/components/ui/media/preview-media.tsx [hunk 2]
```diff
@@ -51,7 +51,7 @@ const Wrapper: FC<{
           )}
         >
           <HeaderActions src={src} />
-          {isArray ? children[0] : children}
+          {isArray ? <span>{children[0]}</span> : <span>{children}</span>}
```
Comment (Innei) [inline apps/desktop/layer/renderer/src/components/ui/media/preview-media.tsx]: What does this modification affect?

Comment (cscnk52) [reply apps/desktop/layer/renderer/src/components/ui/media/preview-media.tsx]: just an eslint problem, i will fix it at morning.

**Review by Innei — APPROVED** [review]

**Review by Innei — APPROVED** [review]
